/**
 * @file src/lib/bot/telegram-bot.options.ts
 *
 * PURPOSE
 * -------
 * Public configuration contract for `TelegramBotModule`. These interfaces are
 * the surface consumers fill in when calling `forRoot` / `forRootAsync`.
 *
 * USAGE
 * -----
 * ```ts
 * TelegramBotModule.forRoot({ token: process.env.BOT_TOKEN!, launch: true });
 * ```
 *
 * KEY EXPORTS
 * -----------
 * - TelegramBotModuleOptions: Synchronous configuration object.
 */

import type { Context, Telegraf } from 'telegraf';

/**
 * Synchronous configuration for `TelegramBotModule`.
 *
 * The async counterparts (`useFactory` / `useClass` / `useExisting`) are
 * generated by `ConfigurableModuleBuilder` and accept a factory returning this
 * same shape.
 */
export interface TelegramBotModuleOptions {
  /**
   * The Bot API token issued by @BotFather (format `123456:ABC-DEF...`). The
   * module throws a {@link import('../common').TelegramConfigError} at bootstrap
   * if this is empty.
   */
  token: string;

  /**
   * Options forwarded verbatim to the `Telegraf` constructor (handler timeout,
   * custom `telegram` agent/test environment, etc.). Optional.
   */
  telegraf?: Partial<Telegraf.Options<Context>>;

  /**
   * Launch options forwarded to `bot.launch()`. When omitted the bot starts in
   * long-polling mode; supply a `webhook` block to run in webhook mode. Has no
   * effect when {@link TelegramBotModuleOptions.launch} is `false`.
   */
  launchOptions?: Telegraf.LaunchOptions;

  /**
   * Whether the module should automatically start the bot on
   * `onApplicationBootstrap` and stop it on shutdown. Defaults to `true`. Set
   * to `false` to take full manual control of the lifecycle (useful in tests
   * and serverless/webhook deployments that mount the callback themselves).
   */
  launch?: boolean;
}
