/**
 * @file src/lib/bot/telegram-bot.options.ts
 *
 * PURPOSE
 * -------
 * Public configuration contract for `TelegramBotModule`. These interfaces are
 * the surface consumers fill in when calling `forRoot` / `forRootAsync`.
 *
 * USAGE
 * -----
 * ```ts
 * TelegramBotModule.forRoot({ token: process.env.BOT_TOKEN!, launch: true });
 * ```
 *
 * KEY EXPORTS
 * -----------
 * - TelegramBotModuleOptions: Synchronous configuration object.
 * - TelegramBotCommandsOptions: Command-menu auto-registration settings.
 */

import type { Context, Telegraf } from 'telegraf';

import type { TelegramMetricsRecorder } from '../common';

/**
 * Settings controlling automatic registration of the bot's command menu
 * (`setMyCommands`) from `@Command` metadata. Opt-in: nothing is sent unless
 * {@link TelegramBotCommandsOptions.autoRegister} is `true`.
 */
export interface TelegramBotCommandsOptions {
  /**
   * When `true`, the registrar derives a `BotCommand[]` payload from every
   * `@Command(name, { description })` declared for this bot and calls
   * `setMyCommands` once per command scope at bootstrap. Defaults to `false`
   * (no `setMyCommands` call is ever made).
   */
  autoRegister?: boolean;
}

/**
 * Settings controlling the `@Scene` / `@WizardScene` subsystem for this bot.
 * Scenes work out of the box with no configuration; this only exists to opt out
 * of the auto-registered session middleware.
 */
export interface TelegramBotScenesOptions {
  /**
   * Whether to auto-register Telegraf's in-memory `session()` middleware (which
   * scenes require for `ctx.session`/`ctx.scene` state) ahead of the scene
   * `Stage`. Defaults to `true`. Set to `false` when you register your own
   * session middleware (e.g. `@telegraf/session` for persistence) via `@Use()`
   * so the scene state is not reset on every update by a second session layer.
   */
  session?: boolean;
}

/**
 * Synchronous configuration for `TelegramBotModule`.
 *
 * The async counterparts (`useFactory` / `useClass` / `useExisting`) are
 * generated by `ConfigurableModuleBuilder` and accept a factory returning this
 * same shape.
 */
export interface TelegramBotModuleOptions {
  /**
   * The Bot API token issued by @BotFather (format `123456:ABC-DEF...`). The
   * module throws a {@link import('../common').TelegramConfigError} at bootstrap
   * if this is empty.
   */
  token: string;

  /**
   * Options forwarded verbatim to the `Telegraf` constructor (handler timeout,
   * custom `telegram` agent/test environment, etc.). Optional.
   */
  telegraf?: Partial<Telegraf.Options<Context>>;

  /**
   * Launch options forwarded to `bot.launch()`. When omitted the bot starts in
   * long-polling mode; supply a `webhook` block to run in webhook mode. Has no
   * effect when {@link TelegramBotModuleOptions.launch} is `false`.
   */
  launchOptions?: Telegraf.LaunchOptions;

  /**
   * Whether the module should automatically start the bot on
   * `onApplicationBootstrap` and stop it on shutdown. Defaults to `true`. Set
   * to `false` to take full manual control of the lifecycle (useful in tests
   * and serverless/webhook deployments that mount the callback themselves).
   */
  launch?: boolean;

  /**
   * Command-menu auto-registration settings. Opt-in via
   * `commands: { autoRegister: true }` to sync the Telegram command menu from
   * `@Command(name, { description })` metadata at bootstrap. Omit to leave the
   * menu untouched.
   */
  commands?: TelegramBotCommandsOptions;

  /**
   * Scene & wizard subsystem settings. Optional — `@Scene`/`@WizardScene`
   * providers are discovered and registered automatically; this only controls
   * the auto-registered session middleware (`scenes: { session: false }`).
   */
  scenes?: TelegramBotScenesOptions;

  /**
   * Metrics recorder for this bot's counters, resolved as the
   * {@link import('../common').TELEGRAM_BOT_METRICS} token. Defaults to a fresh
   * {@link import('../common').InMemoryTelegramMetrics} (readable via
   * `.snapshot()`). Supply a custom recorder — e.g.
   * {@link import('../common').createOpenTelemetryMetrics} — to export the
   * counters to your own observability backend instead.
   */
  metrics?: TelegramMetricsRecorder;
}
