/**
 * @file src/lib/bot/telegram-bot.options.ts
 *
 * PURPOSE
 * -------
 * Public configuration contract for `TelegramBotModule`. These interfaces are
 * the surface consumers fill in when calling `forRoot` / `forRootAsync`.
 *
 * USAGE
 * -----
 * ```ts
 * TelegramBotModule.forRoot({ token: process.env.BOT_TOKEN!, launch: true });
 * ```
 *
 * KEY EXPORTS
 * -----------
 * - TelegramBotModuleOptions: Synchronous configuration object.
 * - TelegramBotCommandsOptions: Command-menu auto-registration settings.
 */

import type { Context, Telegraf } from 'telegraf';

/**
 * Settings controlling automatic registration of the bot's command menu
 * (`setMyCommands`) from `@Command` metadata. Opt-in: nothing is sent unless
 * {@link TelegramBotCommandsOptions.autoRegister} is `true`.
 */
export interface TelegramBotCommandsOptions {
  /**
   * When `true`, the registrar derives a `BotCommand[]` payload from every
   * `@Command(name, { description })` declared for this bot and calls
   * `setMyCommands` once per command scope at bootstrap. Defaults to `false`
   * (no `setMyCommands` call is ever made).
   */
  autoRegister?: boolean;
}

/**
 * Synchronous configuration for `TelegramBotModule`.
 *
 * The async counterparts (`useFactory` / `useClass` / `useExisting`) are
 * generated by `ConfigurableModuleBuilder` and accept a factory returning this
 * same shape.
 */
export interface TelegramBotModuleOptions {
  /**
   * The Bot API token issued by @BotFather (format `123456:ABC-DEF...`). The
   * module throws a {@link import('../common').TelegramConfigError} at bootstrap
   * if this is empty.
   */
  token: string;

  /**
   * Options forwarded verbatim to the `Telegraf` constructor (handler timeout,
   * custom `telegram` agent/test environment, etc.). Optional.
   */
  telegraf?: Partial<Telegraf.Options<Context>>;

  /**
   * Launch options forwarded to `bot.launch()`. When omitted the bot starts in
   * long-polling mode; supply a `webhook` block to run in webhook mode. Has no
   * effect when {@link TelegramBotModuleOptions.launch} is `false`.
   */
  launchOptions?: Telegraf.LaunchOptions;

  /**
   * Whether the module should automatically start the bot on
   * `onApplicationBootstrap` and stop it on shutdown. Defaults to `true`. Set
   * to `false` to take full manual control of the lifecycle (useful in tests
   * and serverless/webhook deployments that mount the callback themselves).
   */
  launch?: boolean;

  /**
   * Command-menu auto-registration settings. Opt-in via
   * `commands: { autoRegister: true }` to sync the Telegram command menu from
   * `@Command(name, { description })` metadata at bootstrap. Omit to leave the
   * menu untouched.
   */
  commands?: TelegramBotCommandsOptions;
}
